### ISSUE TITLE
AudioTrack enum missing values: BACKGROUND and NONE 

### ISSUE THREAD

**Issue by dkobylarz** [alexa/alexa-apis-for-java#15]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request (generic to all classes)
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

I should be able to set desired PlayMediaCommand#audioTrack value from FOREGROUND, BACKGROUND, NONE when building a response with ExecuteCommandsDirective.

## Current Behavior

Current AudioTrack enum (ask-sdk-model version 1.38.0) contains only FOREGROUND and UNKNOWN_TO_SDK_VERSION values.

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change

// A working skill sample code using the SDK is recommended.
Refreshing JSON schema used to generate ask-sdk-model classes.
```

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code using the SDK.
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
(missing enum values cannot be reproduced in code)
```

## Context

I want to have full control over Video component from custom skill code - audioTrack property with complete values list is essential. 

## Your Environment

* ASK SDK Models for Java used:  1.38.0
* ASK SDK for Java used: 2.42.1

**Comment by Shreyas-vgr** [comment]
Released new version with fixes (v1.39.3)
