### ISSUE TITLE
Navigation.SetDestination  is missing

### ISSUE THREAD

**Issue by kokhanchyk** [alexa/alexa-apis-for-java#9]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request (generic to all classes)
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Navigation.SetDestination directive type offered and present in 
com.amazon.ask.model.interfaces.navigation package

## Current Behavior

Currently the Navigation.SetDestination directive type is not offered as a valid type in the Directive type.

## Steps to Reproduce (for bugs)
```
Try to create Navigation.SetDestination request type.
```

## Your Environment

* ASK SDK Models for Java used: 1.29.0
* ASK SDK for Java used: 2.31.0
* Operating System and version: Ubuntu 20.04.1

**Comment by nikhilym** [comment]
Hey @kokhanchyk , thanks for raising this request and sorry for the late response. We are following with the service team to get these directives onboarded. We will work on releasing the new models as soon as the changes are available. Sorry for the inconvenience.

**Comment by sjcomstock67** [comment]
Resolving since this should be fixed. Please re-open if it isn't working.
